SectionVerb {
	EnableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speakers"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
	}
}

SectionDevice."Mic" {
	Comment "Microphone"

	EnableSequence [
		cset "name='TX_AIF1_CAP Mixer DEC0' 1"
		cset "name='TX DEC0 MUX' SWR_MIC"
		cset "name='TX SMIC MUX0' ADC0"
		cset "name='ADC1_MIXER Switch' 1"
		cset "name='ADC1 Switch' 1"
		cset "name='ADC1 Volume' 12"
	]

	DisableSequence [
		cset "name='ADC1 Switch' 0"
		cset "name='ADC1_MIXER Switch' 0"
		cset "name='TX SMIC MUX0' ZERO"
		cset "name='TX_AIF1_CAP Mixer DEC0' 0"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},1"
		CaptureChannels 1
	}
}
